spring.application.name=ariaapp

server.port = 8080

# Supabase PostgreSQL connection
spring.datasource.url=jdbc:postgresql://db.kegrsqwbiqpkajdrnwxw.supabase.co:5432/postgres?user=postgres&password=Iambeast-ariadb
spring.datasource.username=postgres
spring.datasource.password=Iambeast-ariadb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=pVi5WWPe6Dx99lUzRkcTiflzRssuMYwfcBaGLDsKLGA=

# Euler Dependency
eulerpool.api.host=https://api.eulerpool.com
eulerpool.api.token=eu_prod_1774025778852_1zjewjcivg9